name: Mashair
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6


  flutter_screenutil: ^5.0.0+2
  mashir_service:
    path: ../mashir_logic
  flutter_colorpicker: ^1.1.0
  flutter_local_notifications:
  flutter_local_notifications_linux:
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  dotted_line: ^3.2.2
  flutter_bloc: ^8.1.1
  flutter_animate: ^4.5.0
  firebase_core: ^3.4.1
  wave: ^0.2.2
  printing: ^5.6.0
  google_generative_ai: ^0.4.6

  barcode: ^2.2.8
  qr_flutter: ^4.1.0
  path_provider: ^2.0.5
  devicelocale: ^0.8.1


  animated_center_item_list_view: ^0.0.2




  JoDija_view:
    git:
      url: https://github.com/zeftawyapps/jodija_view_module.git


dev_dependencies:
  flutter_test:
   sdk: flutter
  flutter_launcher_icons: ^0.14.0
  flutter_lints: ^3.0.0
flutter_launcher_icons:
  android: "Mashair"
  ios: true
  image_path: "assets/img/icon.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/json/
    - assets/img/
    - assets/svg/
    - assets/img/laocal_image/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: segoescript
        fonts:
         - asset: assets/font/segoescript.ttf
      - family: inputs
        fonts:
         - asset: assets/icons/inputs.ttf



  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
